---
# Required Tools
tools_to_check:
  - brew

# APT 
system_upgrade: true

install_packages: true
packages_to_install_list:
  - curl
  - gnupg
  - apt-transport-https
  - xz-utils
  - gnome-tweaks
  - pip
  - vim
  - git
  - zsh
  - vlc
  - flameshot
  - timeshift
  - xz-utils
  - build-essential

uninstall_packages: true
packages_to_uninstall_list:
  - bcache-tools 
  - byobu
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - landscape-common
  - lxd-agent-loader
  - open-vm-tools
  - popularity-contest
  - sosreport

# BREW
brew_packages_install:
  - gcc
  - thefuck
